### ISSUE TITLE
error when converting h5

### ISSUE THREAD

**Issue by javismiles** [tomgoldstein/loss-landscape#13]
hi

I download Resnet h5 files from
https://drive.google.com/a/cs.umd.edu/file/d/12oxkvfaKcPyyHiOevVNTBzaQ1zAFlNPX/view?usp=sharing

then I try the conversion
python h52vtp.py --surf_file path_to_surf_file --surf_name train_loss --zmax  10 --log

but I get this error

Traceback (most recent call last):
  File "loss-landscape/h52vtp.py", line 259, in <module>
    h5_to_vtp(args.surf_file, args.surf_name, log=args.log, zmax=args.zmax, interp=args.interp)
  File "loss-landscape/h52vtp.py", line 38, in h5_to_vtp
    [xcoordinates, ycoordinates] = np.meshgrid(f['xcoordinates'][:], f['ycoordinates'][:][:])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'xcoordinates' doesn't exist)"

any tips?

and most importantly, can you advice me how to convert .h5 files to .obj mesh files?
thank you so much

**Comment by sudhasubramaniam** [comment]
Did you got solution for this issue? I'm also facing same issue

**Comment by wuuu110** [comment]
Did you got solution？

**Comment by merak0514** [comment]
Did you got solution？
